spring:
  application:
    name: job-status-listener
  profiles:
    active: docker
  cloud:
    config:
      url: http://localhost:8888
    stream:
      bindings:
        tools-execute:
          destination: wacodis.prod.tools.execute
          binder: wacodis_rabbit
          group: messageConsumers
          content-type: application/json
        tools-finished:
          destination: wacodis.prod.tools.finished
          binder: wacodis_rabbit
          group: messageConsumers
          content-type: application/json
        tools-failure:
          destination: wacodis.prod.tools.failure
          binder: wacodis_rabbit
          group: messageConsumers
          content-type: application/json
      binders:
        wacodis_rabbit:
          type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  security:
    enabled: false