server:
  port: 8083
spring:
  application:
    name: job-status-listener
  profiles:
    active: docker
  cloud:
    config:
      url: http://localhost:8888
    stream:
      bindings:
        tools-execute:
          destination: wacodis.test.tools.execute
          binder: wacodis_rabbit
          group: messageConsumers
          content-type: application/json
        tools-finished:
          destination: wacodis.test.tools.finished
          binder: wacodis_rabbit
          group: messageConsumers
          content-type: application/json
        tools-failure:
          destination: wacodis.test.tools.failure
          binder: wacodis_rabbit
          group: messageConsumers
          content-type: application/json
      binders:
        wacodis_rabbit:
          type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
  jobdefinitionapi:
    baseurl: http://localhost:8081
    apiendpoint: /jobDefinitions/jobstatus/
    # httpmethod: PATCH
management:
  security:
    enabled: false